/*
项目日报子系统
MySQL - 5.6.14 : Database - itsboard
*********************************************************************
*/


/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
TRUNCATE TABLE t_pm_task_type;
INSERT INTO `t_pm_task_type` VALUES (1, '项目', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2014-1-15 15:20:17');
INSERT INTO `t_pm_task_type` VALUES (2, '休假', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2014-1-15 15:20:25');
INSERT INTO `t_pm_task_type` VALUES (3, '其他', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2014-1-15 15:20:33');
INSERT INTO `t_pm_task_type` VALUES (4, '借调', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2014-1-15 15:20:43');



/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

